### ISSUE TITLE
Can't use external classes in Gulpfile.ts

### ISSUE THREAD

**Issue by HackPoint** [pleerock/gulpclass#2]
`{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "experimentalAsyncFunctions": true,
    "moduleResolution": "node",
    "removeComments": true,
    "noImplicitAny": false,
    "listFiles": true,
    "noLib": false,
    "outDir": "dist"
  },
  "exclude": [
    "node_modules",
    "server/typings/browser.d.ts",
    "server/typings/browser/**"
  ],
  "files": [
    "server/typings/main.d.ts"
  ],
  "compileOnSave": false
}`

`import { Gulpclass, Task, SequenceTask } from 'gulpclass/Decorators';
import \* as util from 'gulp-util';
import \* as chalk from 'chalk';
import \* as del from 'del';
import wf = require('./server/utils/config/config'); // here is the error issue

@Gulpclass()
export class Gulpfile {
    @Task()
    public clean():void {
        console.log('clean');
        console.log(wf)
        //del([_workflowConfig.DIST_DIR]).then((paths) => {
        //    util.log('Deleted', chalk.yellow(paths && paths.join(', ') || '-'));
        //    done();
        //});
    }
}`

`Error: Cannot find module './server/utils/config/config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at eval (eval at <anonymous> (/Users/gena/ironbuzz/private/web-marina/cms/gulpfile.js:1:90), <anonymous>:10:10)
    at Object.<anonymous> (/Users/gena/ironbuzz/private/web-marina/cms/gulpfile.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
`

**Comment by pleerock** [comment]
Looks like what you are doing is not correct, its not related to this library. Typescript compiler itself give you error: `Error:(12, 21) TS2307: Cannot find module './server/utils/config/config'.`. Maybe you simply need to do `let wf = require('./server/utils/config/config');` ?

**Comment by pleerock** [comment]
closing because of no response from reportee
